apiVersion: v1
kind: Pod
metadata:
  name: second-pod
spec:
  containers:
    - name: nginx
      image: registry.digitalocean.com/si-registry-mirim/my-python-app
      ports:
        - containerPort: 80
